# Generated by Django 6.0.1 on 2026-01-22 11:27

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tat_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(default=tickets.models.generate_ticket_no, editable=False, max_length=20, unique=True),
        ),
    ]
