# Generated by Django 6.0.1 on 2026-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_tat_deadline_alter_ticket_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='problem_solver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solution_provided',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
