# Generated by Django 6.0.1 on 2026-01-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_dashboarduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('password_set', models.BooleanField(default=False)),
            ],
        ),
    ]
