# Generated by Django 6.0.1 on 2026-01-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_helpdeskuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpDeskUser',
        ),
    ]
